NumPy is a linear Algebra library and thats why its so important in Data Science, its incredibly fast, building blocks of C
We will be working mainly with NumPy arrays, vectors or matrices

NumPy Arrays

In [1]:
my_list =[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr= np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#arange was used to create a 1d array in a specific range

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#arrays of all zeroes

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
np.zeros((5,5)) # create 2 d array

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
#array of ones

In [17]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [18]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [19]:
#linspace - it takes no of points as well

In [23]:
np.linspace(0,5,10) # 10 is no of evenly spaced pointss

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [26]:
np.eye(4) # identity matrix of 4*4

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [29]:
np.random.rand(5) # 1-d array of size 5 between 0 and 1 by default

array([ 0.83908678,  0.36274772,  0.7600526 ,  0.49808059,  0.47698381])

In [31]:
np.random.rand(5,5) # 2-d array

array([[ 0.76459172,  0.14075384,  0.70873714,  0.1985104 ,  0.99344081],
       [ 0.61121533,  0.42862184,  0.87153695,  0.13825691,  0.62130863],
       [ 0.42942094,  0.37738136,  0.85730711,  0.53669703,  0.7358609 ],
       [ 0.58002516,  0.50726304,  0.97454617,  0.04872736,  0.16492436],
       [ 0.43909483,  0.29528586,  0.93072837,  0.60674706,  0.50673251]])

In [34]:
np.random.randn(4,4) # normalized distrbution with randn

array([[-0.5238276 ,  1.09023159,  0.78725405,  0.36897181],
       [-0.90667323, -1.91243171, -0.86202562, -2.62950923],
       [-1.06992819,  1.19351387,  0.55121947,  0.08568114],
       [ 0.10885743,  1.10691771,  0.0873816 ,  0.26154377]])

In [36]:
np.random.randint(1,100,6) # random nos array between low and high range

array([29, 45,  9, 20, 39, 76])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
#reshape method common method

In [41]:
arr.reshape(5,5) #converted 1-d to 2-d array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ranarr

array([34, 18, 32, 17,  8, 30, 48, 34, 48, 34])

In [43]:
ranarr.max()

48

In [44]:
ranarr.min()

8

In [45]:
ranarr

array([34, 18, 32, 17,  8, 30, 48, 34, 48, 34])

In [47]:
ranarr.argmax()

6

In [48]:
arr.shape

(25,)

In [51]:
arr= arr.reshape(5,5)

In [52]:
arr.shape

(5, 5)

In [53]:
#datatype of an array

In [56]:
arr.dtype

dtype('int32')

In [57]:
from numpy.random import randint

In [58]:
randint(2,10)

4

In [59]:
#indexing and selection of numpy arrays

In [60]:
#grouping elements

In [61]:
arr= np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[8]

8

In [64]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [65]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [67]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [68]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
#broadcast

In [71]:
arr[0:5] = 100

In [72]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr = arr[0:6]

In [76]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [78]:
slice_of_arr[:]=99

In [79]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [80]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
#slice value changed and also changed original array arr, pass by value

In [82]:
#for copy and not original

In [83]:
arr_copy = arr.copy()

In [84]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr_copy[:]=100

In [89]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [90]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [91]:
#2-d arrays

In [93]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [94]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [95]:
arr_2d[0][0] # getting element in 2d array

5

In [96]:
arr_2d[0]

array([ 5, 10, 15])

In [97]:
arr_2d[2][1]

40

In [99]:
arr_2d[1,2] # comma notation

30

In [100]:
arr_2d[1][2]

30

In [101]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [102]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

array([[10, 15],
       [25, 30],
       [40, 45]])

In [105]:
arr_2d[1:2,:]

array([[20, 25, 30]])

In [106]:
#conditional selection

In [107]:
arr = np.arange(1,11)

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
#getting boolean array out of this

In [111]:
bool_arr = arr>5

In [112]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [113]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [114]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [115]:
arr[arr<3]

array([1, 2])

In [116]:
arr_2d = np.arange(50).reshape(5,10)

In [117]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [118]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [120]:
#Numpy operations on arrays

In [121]:
#array with array , scalars and universal array functions

In [122]:
arr = np.arange(0,11)

In [123]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr+ arr #addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [127]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [128]:
arr + 100 #scalar addition

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [131]:
arr/arr #gives nan where 0/0 occurs , got warning and no error

c:\users\handa\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [133]:
1/arr #got infinity, no error only warning

c:\users\handa\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [134]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [136]:
#universal array functions

In [137]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [138]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [139]:
np.max(arr)

10

In [140]:
arr.max()

10

In [141]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [142]:
np.log(arr)

c:\users\handa\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])